apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-coredns
  namespace: chaos-dns-e2e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-coredns-e2e
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "namespaces"]
  verbs: ["list", "watch", "get"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-coredns-e2e
subjects:
- kind: ServiceAccount
  name: chaos-coredns
  namespace: chaos-dns-e2e
roleRef:
  kind: ClusterRole
  name: chaos-coredns-e2e
  apiGroup: rbac.authorization.k8s.io
